### ISSUE TITLE
Spustenie aplikácie: Invalid API key - ošetriť nevalidný API key

### ISSUE THREAD

**Issue by AdrianBoros1409** [Ipis2P/Ipis2P-Project#3]
- 🔢 dokumentácia OpenWeatherMap API: https://openweathermap.org/guide

**Technické info:** 
-  pri spustení aplikácie sa kontroluje API key
-  tento API key je používaný pre stiahnutie aktuálneho počasia
-  je nutné zabezpečiť to, aby API key bol aktuálny

**Body pre túto úlohu**
- [x] analyzovať ako je možné zabrániť chybnému API key a následne upraviť

**Comment by tomiqo** [comment]
@AdrianBoros1409 je to upravené 👍 , poprosím o kontrolu. Ďakujem.

**Comment by AdrianBoros1409** [comment]
@tomiqo Otestované, je to v poriadku. 
@tomasskk Poprosím review.

**Comment by tomasskk** [comment]
@tomiqo approved - mozes merge

**Comment by tomiqo** [comment]
Mergnuté, zatváram.
